
name: 'facebook_ads'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  facebook_ads:
    materialized: table

vars:
  facebook_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
